console.group("Groupe 1");
console.group("Child Groupe");
console.log("Message One");
console.log("Message Two");
console.group("Grand Child Groupe");
console.log("Message One");
console.log("Message Two");
console.groupEnd();
console.groupEnd();
console.groupEnd();
console.group("Groupe 2");
console.log("Message One");
console.log("Message Two");
console.log("Iam In Console");
console.table(["Ahmad" , "ali" , "elzero" , "mohamad" , "sara"]);
console.error("------------------------");
console.log(typeof "ahmad");
console.log(typeof 2000);
console.log(typeof 23.5);
console.log(typeof true);
console.log(typeof 8989n);
console.log(typeof null);
console.log(typeof undefined);
console.log(typeof function f1(){});
console.log(typeof {name:"ali" , num:1});
console.log(typeof ["ahmad" , 10 , 20000]);